version: '3.7'


services:

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - database/postgres.env
    networks:
      - backend-net
      - pgadmin-net
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=strongpassword
    image: dpage/pgadmin4
    networks:
      - pgadmin-net
      - proxy-pgadmin
    #ports:
    #  - "5000:80"
    restart: always
    volumes:
      - pg-data:/var/lib/pgadmin

  #redis:
  # - backend-net

  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    #deploy:
    environment:
      - DB_SERVER=database
      - DB_NAME=kombinacijadb
      - DB_USER=kombinacijauser
      - DB_PASS=kombinacijapassword
    networks:
      - backend-net
      - proxy-app
    restart: always

  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - proxy-web
    restart: always

  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - app
      - pgadmin
      - web
    networks:
      - proxy-app
      - proxy-pgadmin
      - proxy-web
    ports:
      - "80:80"
    restart: always


networks:
  backend-net:
  pgadmin-net:
  proxy-app:
  proxy-pgadmin:
  proxy-web:


volumes:
  db-data:
  pg-data: