version: '3.3'


services:

  database:
    container_name: database
    build:
      context: database
      dockerfile: database/Dockerfile
    env_file:
      - database/kombinacija.env
      - database/postgres.env
    networks:
      - backend-net
      - pgadmin-net
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@kombinacija.hopto.org
      - PGADMIN_DEFAULT_PASSWORD=verymuchstrongpassword
    image: dpage/pgadmin4
    networks:
      - pgadmin-net
    ports:
      - "5000:80"
    restart: always
    volumes:
      - pg-data:/var/lib/pgadmin

  #redis:
  # - backend-net

  app:
    container_name: app
    build:
      context: backend
      dockerfile: backend/Dockerfile
    depends_on:
      - database
    environment:
      - DB_SERVER=database
    env_file:
      - database/kombinacija.env
    networks:
      - backend-net
      - proxy-app
    restart: always

  web:
    container_name: web
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
    depends_on:
      - app
    networks:
      - proxy-app
    ports:
      - "80:80"
      - "443:443"
    restart: always


networks:
  backend-net:
  pgadmin-net:
  proxy-app:


volumes:
  db-data:
  pg-data: