version: '3.7'


services:

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - database/postgres.env
    networks:
      - backend-net
      - pgadmin-net
    restart: always
    #volumes:

  pgadmin:
    container_name: pgadmin
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=strongpassword
    image: dpage/pgadmin4
    networks:
      - pgadmin-net
    ports:
      - "5000:80"
    restart: always

  #redis:

  app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    #deploy:
    environment:
      - DB_SERVER=database
      - DB_NAME=kombinacijadb
      - DB_USER=kombinacijauser
      - DB_PASS=kombinacijapassword
    networks:
      - backend-net
    ports:
      - "9090:8080"
    restart: always

  #web:

  #reverse-proxy:


networks:
  backend-net:
  pgadmin-net:
  frontend-net: